# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('image', models.ImageField(upload_to='images')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GiftCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.GiftCategory'),
        ),
    ]
