# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200514_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='county',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='street_address1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='town_city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
