# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200525_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
